<div class="container-fluid well text-center" xmlns="http://www.w3.org/1999/html">

    <div class="row" style="margin-bottom: 1em; font-size: 18px">
        <div class="col-md-1 id">
            id
        </div>
        <div class="col-md-3 title">
            title
        </div>
        <div class="col-md-3 author">
            author
        </div>
        <div class="col-md-5">
            image
        </div>

    </div>

    <?php echo $this->tag->form("admin/add"); ?>
    <div class="row" style="line-height: 30px; padding: 9px 0; background-color:#e3e3e3;">
        <div class="col-md-1 id">
            ???
        </div>
        <div class="col-md-3">
            <input type="text" name="title" value="" placeholder="enter title" class="form-control">
        </div>
        <div class="col-md-3">
            <input type="text" name="author" value="" placeholder="enter author" class="form-control">
        </div>
        <div class="col-md-5">
            <input type="text" name="url" value="" placeholder="enter url" class="form-control">
        </div>
    </div>


</div>

<button type="submit" class="btn btn-default pull-right">Add</button>

</form>