<div class="container-fluid well text-center" xmlns="http://www.w3.org/1999/html">

    <div class="row" style="margin-bottom: 1em; font-size: 18px">
        <div class="col-md-1 id">
            id
        </div>
        <div class="col-md-3 title">
            title
        </div>
        <div class="col-md-3 author">
            author
        </div>
        <div class="col-md-5">
            image
        </div>

    </div>

    <?php echo $this->tag->form("admin/save"); ?>
        <div class="row" style="line-height: 30px; padding: 9px 0; background-color:#e3e3e3;">
            <div class="col-md-1 id">
                <input type="text" name="id" value="<?=$image->id?>" class="form-control">
            </div>
            <div class="col-md-3">
                <input type="text" name="title" value="<?=$image->title?>" class="form-control">
            </div>
            <div class="col-md-3">
                <input type="text" name="author" value="<?=$image->athor?>" class="form-control">
            </div>
            <div class="col-md-5">
                <input type="text" name="url" value="<?=$image->url?>" class="form-control">
            </div>
        </div>


</div>

    <button type="submit" class="btn btn-default pull-right">Save</button>

</form>