<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<title>Gallery</title>

		<?php $this->assets->outputCss('header') ?>

		<!--[if IE]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<script>
			document.documentElement.className = 'js';
		</script>
	</head>
	<body>
		<div class="view">
			<section class="page page--mover">
			</section>
			<div class="title-wrap">
				<h1 class="title title--main">Lorem ipsum.</h1>
				<p class="title title--sub">Lorem ipsum dolor sit amet.</p>
			</div>
			<section class="page page--static">
				<div class="page__title">
					<h2 class="page__title-main">Lorem ipsum dolor sit amet.</h2>
					<p class="page__title-sub">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id, quia?</p>
				</div>

				<ul class="grid">
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/1.jpg" alt="Some image" />
							<h3 class="grid__item-title">Natural saturation effects</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/2.jpg" alt="Some image" />
							<h3 class="grid__item-title">Auto-color and light</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/3.jpg" alt="Some image" />
							<h3 class="grid__item-title">That special blur</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/4.jpg" alt="Some image" />
							<h3 class="grid__item-title">Drama where you need it</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/5.jpg" alt="Some image" />
							<h3 class="grid__item-title">Realistic depth</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/6.jpg" alt="Some image" />
							<h3 class="grid__item-title">The common, but special</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/7.jpg" alt="Some image" />
							<h3 class="grid__item-title">Natural saturation effects</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/8.jpg" alt="Some image" />
							<h3 class="grid__item-title">That special blur</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/9.jpg" alt="Some image" />
							<h3 class="grid__item-title">Auto-color and light</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/1.jpg" alt="Some image" />
							<h3 class="grid__item-title">Natural saturation effects</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/2.jpg" alt="Some image" />
							<h3 class="grid__item-title">Auto-color and light</h3>
						</a>
					</li>
					<li class="grid__item">
						<a class="grid__link" href="#">
							<img class="grid__img" src="img/photos/3.jpg" alt="Some image" />
							<h3 class="grid__item-title">That special blur</h3>
						</a>
					</li>
				</ul>

			</section>

			<div class="device">
				<div class="device__screen"></div>
			</div>

			<button id="showgrid" class="button button--view" aria-label="Show me more">
				<svg width="100%" height="100%" viewBox="0 0 310 177" preserveAspectRatio="xMidYMid meet">
					<path fill="#FFFFFF" d="M159.875,174.481L306.945,27.41c2.93-2.929,2.93-7.678,0-10.606L292.803,2.661c-1.406-1.407-3.314-2.197-5.303-2.197c-1.989,0-3.896,0.79-5.303,2.197L154.572,130.287L26.946,2.661c-1.406-1.407-3.314-2.197-5.303-2.197c-1.989,0-3.897,0.79-5.303,2.197L2.197,16.804C0.733,18.269,0,20.188,0,22.107s0.732,3.839,2.197,5.303l147.071,147.071C152.197,177.411,156.945,177.411,159.875,174.481L159.875,174.481z" />
				</svg>
			</button>
			<!-- Related demos -->
			<section class="content content--related">

			</section>
		</div><!-- /view -->
		<?php $this->assets->outputJs('footer') ?>
	</body>
</html>
