<div class="text-center well container-fluid" style="padding: 10px !important;">
    <div class="row">
        <a role="button" href="/phalcon_gallery" type="button" class="btn btn-success pull-left">Come back to MainPage</a>
            <div style="line-height: 31px; padding-right: 185px; font-size: 18px; " class="text-center"> AdminRoom </div>

    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                <a href="/phalcon_gallery/admin/management/" class="list-group-item active">Home</a>
                <a href="/phalcon_gallery/admin/add/" class="list-group-item">Add</a>
                <a href="photographers" class="list-group-item">Photographers</a>
                <a href="citations" class="list-group-item">Citations</a>
                <a href="#" class="list-group-item">Vestibulum at eros</a>
            </div>
        </div>
        <div class="col-md-8">
            <?php echo $this->getContent(); ?>
        </div>
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Lorem ipsum dolor sit amet.
                    </div>
                </div>
                <div class="panel panel-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, natus?
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Lorem ipsum dolor sit amet.
                    </div>
                </div>
                <div class="panel panel-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, natus?
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Lorem ipsum dolor sit amet.
                    </div>
                </div>
                <div class="panel panel-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, natus?
                </div>
            </div>

        </div>
    </div>
</div>

