<p class="text-center well">AdminRoom</p>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="#" class="list-group-item active">Cras justo odio</a>
                <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item">Morbi leo risus</a>
                <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item">Vestibulum at eros</a>
            </div>
        </div>
        <div class="col-md-6">
            <?php echo $this->getContent(); ?>
        </div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Lorem ipsum dolor sit amet.
                    </div>
                </div>
                <div class="panel panel-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, natus?
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Lorem ipsum dolor sit amet.
                    </div>
                </div>
                <div class="panel panel-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, natus?
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Lorem ipsum dolor sit amet.
                    </div>
                </div>
                <div class="panel panel-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, natus?
                </div>
            </div>

        </div>
    </div>
</div>

